import{puzzles}from'./puzzles.js';
const key='mochi-iq-garden-v1';
export const fresh=()=>({started:false,name:'Mochi',coins:60,xp:0,level:1,pet:{happiness:82,hunger:74,energy:88,cleanliness:91,health:100},sleeping:false,lastSimulationTime:Date.now(),usedMossyPuzzleIds:[],solved:{},attempts:{},inventory:['apple'],equipped:{skin:'green',accessory:''},streak:1,lastDay:new Date().toLocaleDateString('en-CA'),progressDay:new Date().toLocaleDateString('en-CA'),dailyCompleted:0,interactions:0,sound:false,decor:[]});
const clamp=(n)=>Math.max(0,Math.min(100,n));
export function simulatePet(s,now=Date.now()){
 const last=Number(s.lastSimulationTime)||now, elapsed=Math.min(24*3600000,Math.max(0,now-last));if(!elapsed)return{...s,lastSimulationTime:now};
 const p={...s.pet};let cursor=now-elapsed;
 while(cursor<now){const hour=new Date(cursor).getHours(),sleeping=hour>=22||hour<7,stop=Math.min(now,cursor+Math.min(3600000-(cursor%3600000),now-cursor)),h=(stop-cursor)/3600000;
  p.hunger=clamp(p.hunger-2*h);p.cleanliness=clamp(p.cleanliness-1.5*h);p.energy=clamp(p.energy+(sleeping?10:-1)*h);
  const happinessRate=1+(p.hunger<20?.45:0)+(p.energy<20?.35:0)+(p.cleanliness<20?.35:0);p.happiness=clamp(p.happiness-happinessRate*h);
  const poor=(p.hunger<15&&p.energy<15)||(p.cleanliness<15&&p.hunger<15),well=p.hunger>=35&&p.energy>=25&&p.cleanliness>=30;p.health=clamp(p.health+(poor?-1:well?.5:0)*h);cursor=stop;
 }
 const sleepingNow=new Date(now).getHours()>=22||new Date(now).getHours()<7;
 return{...s,pet:Object.fromEntries(Object.entries(p).map(([k,v])=>[k,Math.round(v*10)/10])),sleeping:sleepingNow,lastSimulationTime:now};
}
export function load(){try{const x=JSON.parse(localStorage.getItem(key)),base=fresh();if(!x||typeof x!=='object'||Array.isArray(x))return base;const clampValue=(v,d)=>Number.isFinite(v)?Math.max(0,Math.min(100,v)):d,pet={};for(const k of Object.keys(base.pet))pet[k]=clampValue(x.pet?.[k],base.pet[k]);const rawSolved=x.solved&&typeof x.solved==='object'&&!Array.isArray(x.solved)?x.solved:{},solved={};for(const[id,v]of Object.entries(rawSolved)){const n=Number(id);if(n>=1&&n<=120&&v&&typeof v==='object')solved[n]={stars:Math.max(1,Math.min(3,Math.floor(Number(v.stars)||1))),time:Math.max(1,Math.floor(Number(v.time)||1)),moves:Math.max(1,Math.floor(Number(v.moves)||1))}}const loaded={...base,...x,name:typeof x.name==='string'?x.name.slice(0,16):base.name,started:!!x.started,coins:Math.max(0,Math.floor(Number(x.coins)||0)),xp:Math.max(0,Math.floor(Number(x.xp)||0)),level:Math.max(1,Math.floor(Number(x.level)||1)),pet,solved,sleeping:!!x.sleeping,usedMossyPuzzleIds:[...new Set([...(Array.isArray(x.usedMossyPuzzleIds)?x.usedMossyPuzzleIds.filter(v=>typeof v==='string'):[]),...Object.keys(solved).map(id=>`mossy-${String(id).padStart(3,'0')}`)])],lastSimulationTime:Number.isFinite(x.lastSimulationTime)?x.lastSimulationTime:(Number.isFinite(x.savedAt)?x.savedAt:Date.now()),attempts:x.attempts&&typeof x.attempts==='object'&&!Array.isArray(x.attempts)?x.attempts:{},inventory:Array.isArray(x.inventory)?[...new Set(x.inventory.filter(v=>typeof v==='string'))]:base.inventory,decor:Array.isArray(x.decor)?x.decor.filter(v=>typeof v==='string'):[],equipped:{skin:x.equipped?.skin==='gold'?'gold':'green',accessory:['crown','glasses','bow'].includes(x.equipped?.accessory)?x.equipped.accessory:''},streak:Math.max(1,Math.floor(Number(x.streak)||1)),dailyCompleted:Math.max(0,Math.floor(Number(x.dailyCompleted)||0)),progressDay:typeof x.progressDay==='string'?x.progressDay:base.progressDay,interactions:Math.max(0,Math.floor(Number(x.interactions)||0)),sound:!!x.sound,lastDay:typeof x.lastDay==='string'?x.lastDay:base.lastDay};return simulatePet(loaded)}catch{return fresh()}}
export function save(s){try{localStorage.setItem(key,JSON.stringify({...s,savedAt:Date.now()}));return true}catch{return false}}
export function xpLevel(x){return Math.floor((Math.sqrt(1+8*x/100)-1)/2)+1}
export function levelProgress(x){const level=xpLevel(x),start=100*(level-1)*level/2,next=100*level*(level+1)/2;return Math.max(0,Math.min(100,(x-start)/(next-start)*100))}
export function progressCount(s){return Object.keys(s.solved||{}).length}
export const shopItems=[{id:'apple',name:'Apple snack',icon:'🍎',price:0,kind:'food'},{id:'berry',name:'Berry bowl',icon:'🫐',price:20,kind:'food'},{id:'tulip',name:'Tulip patch',icon:'🌷',price:55,kind:'garden'},{id:'crown',name:'Daisy crown',icon:'🌼',price:80,kind:'accessory'},{id:'glasses',name:'Round specs',icon:'🤓',price:95,kind:'accessory'},{id:'pond',name:'Tiny pond',icon:'🪷',price:120,kind:'garden'},{id:'gold',name:'Honey glow',icon:'🐸',price:180,kind:'skin'}];
export function care(s,kind){const p={...s.pet};if(kind==='feed'){p.hunger=Math.min(100,p.hunger+24);p.happiness=Math.min(100,p.happiness+5)}if(kind==='play'){p.happiness=Math.min(100,p.happiness+16);p.energy=Math.max(0,p.energy-8)}if(kind==='pet')p.happiness=Math.min(100,p.happiness+10);if(kind==='clean')p.cleanliness=Math.min(100,p.cleanliness+16);return{...s,pet:p,interactions:s.interactions+1,lastSimulationTime:Date.now()}}
export const achievements=[['First Step','Solve your first puzzle','🌱',s=>progressCount(s)>=1],['Brain Training','Solve 10 puzzles','🧠',s=>progressCount(s)>=10],['Puzzle Explorer','Solve 25 puzzles','🧭',s=>progressCount(s)>=25],['Logic Master','Solve 50 puzzles','🏆',s=>progressCount(s)>=50],['Almost There','Solve 100 puzzles','✨',s=>progressCount(s)>=100],['IQ Champion','Complete all 120 challenges','👑',s=>progressCount(s)>=120],['Perfect','Earn 3 stars on 10 puzzles','⭐',s=>Object.values(s.solved).filter(v=>v.stars===3).length>=10],['Streak Master','Play 7 days in a row','🔥',s=>s.streak>=7],['Mochi’s Best Friend','Interact with Mochi 50 times','💚',s=>s.interactions>=50]];
