import React,{useEffect,useMemo,useRef,useState}from'react';
import{RotateCw,Undo2,Move}from'lucide-react';
import{rotateShape,validateState,startingPlacements,hasMeaningfulRotation,sameOrientation,normalizeRotation,magneticSnapCandidate}from'./puzzles.js';

const shapeBounds=cells=>({w:Math.max(...cells.map(c=>c.x))+1,h:Math.max(...cells.map(c=>c.y))+1});
function boardValidity(p,pieceId,pos,placements){const d=p.data,piece=d.pieces.find(q=>q.id===pieceId),blocked=new Set(d.blocked.map(c=>`${c.x},${c.y}`));for(const c of rotateShape(piece.cells,pos.rotation)){const x=pos.x+c.x,y=pos.y+c.y,key=`${x},${y}`;if(x<0||x>=d.cols||y<0||y>=d.rows)return{valid:false,reason:'That shape would hang over the board.'};if(blocked.has(key))return{valid:false,reason:'A piece cannot cover a rock.'};for(const other of d.pieces){if(other.id===pieceId)continue;const op=placements[other.id];if(!Number.isInteger(op?.x))continue;if(rotateShape(other.cells,op.rotation).some(q=>q.x+op.x===x&&q.y+op.y===y))return{valid:false,reason:'Pieces need their own space.'}}}return{valid:true}}

export function PuzzleTable({puzzle,onSolved,onMove,hintLevel=0,onMessage,onSound=()=>{}}){const rootRef=useRef(null),boardRef=useRef(null),dragGhostRef=useRef(null),dragRef=useRef(null),frameRef=useRef(0),solvedRef=useRef(false);const[placements,setPlacements]=useState(()=>startingPlacements(puzzle)),[selectedId,setSelectedId]=useState(puzzle.data.pieces[0]?.id||null),[drag,setDrag]=useState(null),[notice,setNotice]=useState(''),[failCount,setFailCount]=useState(0),[invalidTick,setInvalidTick]=useState(0),[cellSize,setCellSize]=useState(48),[turnPulse,setTurnPulse]=useState({pieceId:null,count:0});const d=puzzle.data,pieces=d.pieces,selected=pieces.find(p=>p.id===selectedId),specialMap=useMemo(()=>new Map(d.specialTiles.map(t=>[`${t.x},${t.y}`,t.kind])),[d.specialTiles]);
 useEffect(()=>{const resize=()=>setCellSize(Math.min(54,Math.max(32,(window.innerWidth-70)/d.cols)));resize();window.addEventListener('resize',resize);return()=>window.removeEventListener('resize',resize)},[d.cols]);
 useEffect(()=>{const g=dragRef.current;if(dragGhostRef.current&&g)dragGhostRef.current.style.transform=`translate3d(${g.startX-g.grabX*cellSize}px,${g.startY-g.grabY*cellSize}px,0)`},[drag?.pieceId,cellSize]);
 useEffect(()=>{const g=dragRef.current;if(dragGhostRef.current&&g)dragGhostRef.current.style.transform=`translate3d(${g.startX-g.grabX*cellSize}px,${g.startY-g.grabY*cellSize}px,0)`},[drag?.pieceId,cellSize]);
 const tell=msg=>{setNotice(msg);onMessage?.(msg);setTimeout(()=>setNotice(''),1900)};
 function candidateAt(e,activeDrag){const rect=boardRef.current?.getBoundingClientRect();if(!rect)return null;const inset=Number.parseFloat(getComputedStyle(boardRef.current).getPropertyValue('--board-inset'))||12,cw=(rect.width-inset*2)/d.cols,ch=(rect.height-inset*2)/d.rows,col=Math.floor((e.clientX-rect.left-inset)/cw),row=Math.floor((e.clientY-rect.top-inset)/ch);if(col<0||col>=d.cols||row<0||row>=d.rows)return null;const piece=d.pieces.find(p=>p.id===activeDrag.pieceId),solution=piece?.solution;if(solution){const tx=rect.left+inset+(solution.x+activeDrag.anchor.x+.5)*cw,ty=rect.top+inset+(solution.y+activeDrag.anchor.y+.5)*ch,magnet=magneticSnapCandidate({pointerX:e.clientX,pointerY:e.clientY,targetX:tx,targetY:ty,cellSize:Math.min(cw,ch),solution,rotation:activeDrag.rotation});if(magnet)return magnet}return{x:col-activeDrag.anchor.x,y:row-activeDrag.anchor.y,rotation:activeDrag.rotation}}
 function beginDrag(e,pieceId,anchor,target){if(e.button!==undefined&&e.button!==0)return;e.preventDefault();const current=placements[pieceId],rot=current.rotation||0,source=target?.getBoundingClientRect?.()||e.target.getBoundingClientRect(),cell=Math.max(1,Math.min(source.width,source.height));setSelectedId(pieceId);onSound('snap');dragRef.current={pointerId:e.pointerId,pieceId,anchor:anchor||{x:0,y:0},rotation:rot,startX:e.clientX,startY:e.clientY,moved:false,grabX:(e.clientX-source.left)/cell,grabY:(e.clientY-source.top)/cell,candidateKey:''};setDrag({pieceId,rotation:rot,following:true});try{rootRef.current?.setPointerCapture(e.pointerId)}catch{}}
 function pointerMove(e){const g=dragRef.current;if(!g||g.pointerId!==e.pointerId)return;if(!g.moved&&Math.hypot(e.clientX-g.startX,e.clientY-g.startY)<3)return;g.moved=true;const pointerX=e.clientX,pointerY=e.clientY;if(frameRef.current)cancelAnimationFrame(frameRef.current);frameRef.current=requestAnimationFrame(()=>{if(dragGhostRef.current)dragGhostRef.current.style.transform=`translate3d(${pointerX-g.grabX*cellSize}px,${pointerY-g.grabY*cellSize}px,0)`});const candidate=candidateAt(e,g),key=candidate?`${candidate.x},${candidate.y},${candidate.rotation}`:'outside';if(key!==g.candidateKey){g.candidateKey=key;setDrag({pieceId:g.pieceId,rotation:g.rotation,following:true,candidate,validity:candidate?boardValidity(puzzle,g.pieceId,candidate,placements):null})}}
 function maybeSolved(next){if(solvedRef.current)return;const result=validateState(puzzle,next);if(result.valid){solvedRef.current=true;onSolved(next);return}if(pieces.every(piece=>Number.isInteger(next[piece.id]?.x)&&Number.isInteger(next[piece.id]?.y)))tell(result.reason)}
 function pointerUp(e){const g=dragRef.current;if(!g||g.pointerId!==e.pointerId)return;dragRef.current=null;if(frameRef.current)cancelAnimationFrame(frameRef.current);setDrag(null);if(!g.moved)return;onMove?.();const candidate=candidateAt(e,g);if(!candidate){const n=failCount+1;setFailCount(n);setInvalidTick(x=>x+1);onSound('error');tell(n>=3?`Mochi: Try the ${pieces[0].name} piece first!`:'A gentle nudge—drop a piece over the board.');return}const check=boardValidity(puzzle,g.pieceId,candidate,placements),piece=pieces.find(p=>p.id===g.pieceId),target=piece.solution,stageMisrotatedSnap=!!candidate.magnetic&&candidate.x===target.x&&candidate.y===target.y&&hasMeaningfulRotation(piece)&&!sameOrientation(piece,candidate.rotation,target.rotation);if(!check.valid&&!stageMisrotatedSnap){const n=failCount+1;setFailCount(n);setInvalidTick(x=>x+1);onSound('error');tell(n>=3?`Mochi: Try moving the ${pieces[0].name} piece first!`:check.reason);return}const next={...placements,[g.pieceId]:{...candidate,magnetStaged:stageMisrotatedSnap}};setPlacements(next);setFailCount(0);setSelectedId(g.pieceId);onSound('snap');maybeSolved(next)}
 function cancelDrag(e){if(e&&dragRef.current?.pointerId!==e.pointerId)return;dragRef.current=null;if(frameRef.current)cancelAnimationFrame(frameRef.current);setDrag(null)}
 function rotateSelected(){if(!selected)return;const cur=placements[selected.id],candidate={...cur,rotation:normalizeRotation((cur.rotation||0)+1)};let rotationCheck={valid:true};if(Number.isInteger(cur.x)){rotationCheck=boardValidity(puzzle,selected.id,candidate,placements);if(!rotationCheck.valid&&!cur.magnetStaged){setInvalidTick(x=>x+1);onSound('error');tell(rotationCheck.reason);return}}const reachesTarget=Number.isInteger(cur.x)&&cur.x===selected.solution.x&&cur.y===selected.solution.y&&sameOrientation(selected,candidate.rotation,selected.solution.rotation),nextPosition={...candidate,magnetStaged:cur.magnetStaged&&!(reachesTarget&&rotationCheck.valid)};const next={...placements,[selected.id]:nextPosition};setTurnPulse(p=>({pieceId:selected.id,count:p.count+1}));setPlacements(next);onMove?.();onSound('rotate');tell(`${selected.name} turned ${candidate.rotation*90}°`);if(Number.isInteger(candidate.x))maybeSolved(next)}
 function returnSelected(){if(!selected||!Number.isInteger(placements[selected.id]?.x))return;const next={...placements,[selected.id]:{x:null,y:null,rotation:placements[selected.id].rotation}};setPlacements(next);onMove?.();solvedRef.current=false}
 function placeByTap(pieceId,x,y){const pos=placements[pieceId],candidate={x,y,rotation:pos.rotation||0},check=boardValidity(puzzle,pieceId,candidate,placements);onMove?.();if(!check.valid){setInvalidTick(n=>n+1);tell(check.reason);return}const next={...placements,[pieceId]:candidate};setPlacements(next);setSelectedId(pieceId);onSound('snap');maybeSolved(next)}
 function boardClick(e,x,y){if(e.target.closest('.board-piece-layer'))return;if(!selectedId)return;placeByTap(selectedId,x,y)}
 function handleKeys(e){if(e.key.toLowerCase()==='r'){e.preventDefault();rotateSelected()}if(e.key==='Escape'){setSelectedId(null)}}
 const solutionPiece=hintLevel>=3?pieces[0]:null,solutionPos=solutionPiece?solutionPiece.solution:null,solutionShape=solutionPiece?rotateShape(solutionPiece.cells,solutionPos.rotation):[];
 const cells=[];for(let y=0;y<d.rows;y++)for(let x=0;x<d.cols;x++){const blocked=d.blocked.some(c=>c.x===x&&c.y===y),kind=specialMap.get(`${x},${y}`);cells.push(<div key={`${x},${y}`} role="gridcell" aria-label={blocked?'Rock tile':kind?`${kind} tile`:`Board cell row ${y+1}, column ${x+1}`} className={`board-cell ${blocked?'rock-cell':''} ${kind?`special-${kind}`:''}`} onClick={e=>!blocked&&boardClick(e,x,y)}>{kind&&<span className="board-marker">{kind==='water'?'💧':'🌸'}</span>}{blocked&&<span className="rock-marker">✿</span>}</div>)}
 const placedTiles=[];for(const piece of pieces){const pos=placements[piece.id];if(!Number.isInteger(pos?.x))continue;const shape=rotateShape(piece.cells,pos.rotation);for(const c of shape){const x=pos.x+c.x,y=pos.y+c.y;if(x<0||x>=d.cols||y<0||y>=d.rows)continue;const tileKind=specialMap.get(`${x},${y}`),orientationPending=pos.x===piece.solution.x&&pos.y===piece.solution.y&&hasMeaningfulRotation(piece)&&!sameOrientation(piece,pos.rotation,piece.solution.rotation);placedTiles.push(<button key={`${piece.id}-${c.x}-${c.y}`} className={`board-piece-cell ${selectedId===piece.id?'selected':''} ${orientationPending?'orientation-pending':''}`} style={{gridColumn:x+1,gridRow:y+1,'--piece-color':piece.color}} aria-label={`${piece.name} tile${tileKind?`, covering ${tileKind}`:''}`} data-piece-cell="true" data-piece-id={piece.id} data-cell-x={c.x} data-cell-y={c.y}>{tileKind&&<span className="piece-special-marker" aria-hidden="true">{tileKind==='flower'?'🌸':'💧'}</span>}</button>);}}
 const ghostTiles=[];if(drag?.candidate){const piece=pieces.find(p=>p.id===drag.pieceId),shape=rotateShape(piece.cells,drag.candidate.rotation);for(const c of shape){const x=drag.candidate.x+c.x,y=drag.candidate.y+c.y;if(x>=0&&x<d.cols&&y>=0&&y<d.rows)ghostTiles.push(<div key={`g-${x}-${y}`} className={`ghost-piece-cell ${drag.validity?.valid?'ghost-valid':'ghost-invalid'}`} style={{gridColumn:x+1,gridRow:y+1,'--piece-color':piece.color}}/>)} }
 const hintTiles=[];if(solutionPiece&&solutionPos&& !Number.isInteger(placements[solutionPiece.id]?.x)){for(const c of solutionShape)hintTiles.push(<div key={`h-${c.x}-${c.y}`} className="hint-piece-cell" style={{gridColumn:solutionPos.x+c.x+1,gridRow:solutionPos.y+c.y+1}}/>)}
 const draggedPiece=drag&&pieces.find(p=>p.id===drag.pieceId),draggedShape=draggedPiece&&rotateShape(draggedPiece.cells,drag?.candidate?.rotation??drag?.rotation??placements[draggedPiece.id].rotation),draggedBounds=draggedShape&&shapeBounds(draggedShape);
 return <div ref={rootRef} className="packing-game" onPointerDown={e=>{const target=e.target.closest('[data-piece-cell]');if(!target)return;beginDrag(e,target.dataset.pieceId,{x:Number(target.dataset.cellX),y:Number(target.dataset.cellY)},target)}} onPointerMove={pointerMove} onPointerUp={pointerUp} onPointerCancel={cancelDrag} onLostPointerCapture={cancelDrag} onKeyDown={handleKeys}>
  <div className="packing-brief"><div className="brief-copy"><div className="brief-eyebrow">MOCHI’S GARDEN CHALLENGE</div><b>Fit every shape into the open spaces and match its turn marker.</b><span>Drag a piece, drop it on the board, and rotate it when it helps.</span></div><div className="brief-mochi">🐸 <i>{notice||'Can you solve this one?'}</i></div></div>
  {draggedPiece&&<div ref={dragGhostRef} className="drag-follow-shape" style={{gridTemplateColumns:`repeat(${draggedBounds.w},${cellSize}px)`,gridTemplateRows:`repeat(${draggedBounds.h},${cellSize}px)`}}>{draggedShape.map(c=><span key={`${c.x}-${c.y}`} style={{gridColumn:c.x+1,gridRow:c.y+1,'--piece-color':draggedPiece.color}}/>)}</div>}
  <div className={`puzzle-table ${invalidTick?`nudge-${invalidTick%2}`:''}`} key={puzzle.id}>
   <div className="packing-board-frame"><div className="packing-board" ref={boardRef} role="grid" aria-label={`${d.cols} by ${d.rows} garden puzzle board`} style={{'--board-inset':'12px',width:`${cellSize*d.cols+24}px`,height:`${cellSize*d.rows+24}px`,gridTemplateColumns:`repeat(${d.cols},${cellSize}px)`,gridTemplateRows:`repeat(${d.rows},${cellSize}px)`}}>{cells}<div className="board-piece-layer" style={{gridTemplateColumns:`repeat(${d.cols},${cellSize}px)`,gridTemplateRows:`repeat(${d.rows},${cellSize}px)`}}>{placedTiles}{hintTiles}{ghostTiles}</div></div><div className="board-legend"><span>🌸 cover the blossom</span><span>💧 cover the pond tile</span><span>✿ rock · keep clear</span></div></div>
   <aside className="piece-panel"><div className="piece-panel-title"><div><small>YOUR PIECES</small><b>{pieces.filter(p=>Number.isInteger(placements[p.id]?.x)).length} / {pieces.length} placed</b></div><span>Drag onto board</span></div><div className="piece-tray">{pieces.map(piece=>{const pos=placements[piece.id],shape=rotateShape(piece.cells,pos.rotation||0),bound=shapeBounds(shape),isPlaced=Number.isInteger(pos.x),locked=hintLevel>=2&&piece.id===pieces[0].id,turnRule=hasMeaningfulRotation(piece)?{rotation:piece.solution.rotation}:null,turnRuleMatches=turnRule&&sameOrientation(piece,pos.rotation,turnRule.rotation),coverRule=d.constraints.find(c=>c.type==='cover'&&c.pieceId===piece.id);return <button key={piece.id} className={`tray-piece ${selectedId===piece.id?'chosen':''} ${isPlaced?'in-board':''} ${locked?'hinted':''} ${drag?.pieceId===piece.id?'being-dragged':''}`} aria-label={`${piece.name} piece${isPlaced?' on board':''}`} onClick={()=>{setSelectedId(piece.id);onSound('click')}}><div className={`tray-shape ${turnPulse.pieceId===piece.id?`turn-${turnPulse.count%2}`:''}`} style={{gridTemplateColumns:`repeat(${bound.w},19px)`,gridTemplateRows:`repeat(${bound.h},19px)`}} data-piece-cell="true" data-piece-id={piece.id} data-cell-x="0" data-cell-y="0">{shape.map(c=><span key={`${c.x}-${c.y}`} className="tray-shape-cell" style={{gridColumn:c.x+1,gridRow:c.y+1,'--piece-color':piece.color}} data-piece-cell="true" data-piece-id={piece.id} data-cell-x={c.x} data-cell-y={c.y}/>)}</div><span className="tray-label">{piece.name}</span>{turnRule&&<i className={`turn-mark ${turnRuleMatches?'turn-ok':'turn-required'}`} aria-label={`Current turn ${pos.rotation*90} degrees; target ${turnRule.rotation*90} degrees`}>↻ {pos.rotation*90}° / {turnRule.rotation*90}°</i>}{coverRule&&<i className="special-mark">{coverRule.kind==='flower'?'🌸':'💧'}</i>}</button>})}</div>
    <div className="piece-controls"><span className="selected-label">{selected?`Selected: ${selected.name}`:'Select a piece'}</span><button className="rotate-control" aria-label={selected?`Rotate ${selected.name} 90 degrees`:"Select a piece to rotate"} disabled={!selected} onPointerDown={e=>e.stopPropagation()} onClick={e=>{e.stopPropagation();rotateSelected()}}><RotateCw size={17}/> Rotate 90°</button><button className="return-control" disabled={!selected||!Number.isInteger(placements[selected.id]?.x)} onClick={returnSelected}><Undo2 size={16}/> Return</button></div>
    <div className="rule-list"><b>Garden rules</b><span>Every open cell must be filled. Pieces cannot overlap or cover rocks.</span>{d.rules.map((rule,i)=><span key={i}>✦ {rule}</span>)}</div>
   </aside>
  </div>
  {notice&&<div className="puzzle-notice" role="status">{notice}</div>}
  <div className="packing-footnote"><Move size={14}/> Tap a piece, then a board cell to place it. Press <kbd>R</kbd> to rotate.</div>
 </div>
}
