// Deterministic polyomino packing puzzles and a grid-state exact-cover solver.
const seed=n=>{let x=(n*2654435761)>>>0;return()=>{x^=x<<13;x^=x>>>17;x^=x<<5;return(x>>>0)/4294967296}};
export const tierFor=id=>id<=20?'Tutorial':id<=50?'Easy · Medium':id<=80?'Medium':id<=105?'Hard':'Expert';
const colors=['#79b9c4','#ef9e78','#9c91c8','#8db96a','#e0b75f','#d981a0','#77a0d1','#8f9f86','#d78b69','#79aa9b'];
const normalize=cells=>{const mx=Math.min(...cells.map(c=>c.x)),my=Math.min(...cells.map(c=>c.y));return cells.map(c=>({x:c.x-mx,y:c.y-my})).sort((a,b)=>a.y-b.y||a.x-b.x)};
export function rotateShape(cells,rot){let out=normalize(cells);for(let i=0;i<((rot%4)+4)%4;i++){const h=Math.max(...out.map(c=>c.y))+1;out=normalize(out.map(c=>({x:h-1-c.y,y:c.x})))}return out}
const dims=cells=>({w:Math.max(...cells.map(c=>c.x))+1,h:Math.max(...cells.map(c=>c.y))+1});
const rotatePoint=(p,rot,w,h)=>rot===0?{x:p.x,y:p.y}:rot===1?{x:h-1-p.y,y:p.x}:rot===2?{x:w-1-p.x,y:h-1-p.y}:{x:p.y,y:w-1-p.x};
function sizes(total,r){const count=Math.ceil(total/4),out=[];let left=total;for(let i=0;i<count;i++){const n=count-i-1,opts=[3,4,5].filter(x=>left-x>=3*n&&left-x<=5*n);const v=opts[Math.floor(r()*opts.length)]??4;out.push(v);left-=v}return out}
function snake(cols,rows){const out=[];for(let y=0;y<rows;y++){const xs=Array.from({length:cols},(_,x)=>x);if(y%2)xs.reverse();for(const x of xs)out.push({x,y})}return out}
function geometry(id,r){if(id<=20)return{cols:4,rows:4,blocked:0};if(id<=50)return{cols:5,rows:4,blocked:Math.floor((id-21)/10)};if(id<=80)return{cols:5,rows:5,blocked:1+(id%4)};if(id<=105)return{cols:6,rows:5,blocked:2+(id%4)};return{cols:7,rows:6,blocked:4+(id%4)}}
const signature=cells=>normalize(cells).map(c=>`${c.x},${c.y}`).join(';');
function makePuzzle(id){const r=seed(id),tier=tierFor(id),g=geometry(id,r),full=snake(g.cols,g.rows),playableCount=full.length-g.blocked,playable=full.slice(0,playableCount),blocked=full.slice(playableCount),groups=sizes(playableCount,r),regionGroups=[];let cursor=0;for(const size of groups){regionGroups.push(playable.slice(cursor,cursor+size));cursor+=size}
 const rotationRulesCount=id<=20?0:id<=50?1:id<=80?2:id<=105?3:groups.length;
 const pieces=regionGroups.map((group,i)=>{const gx=Math.min(...group.map(c=>c.x)),gy=Math.min(...group.map(c=>c.y)),relative=group.map(c=>({x:c.x-gx,y:c.y-gy})),goalRotation=id<=20?0:Math.floor(r()*4),canonical=rotateShape(relative,(4-goalRotation)%4),d=dims(canonical);return{id:`p${i+1}`,name:['Pond lily','Clover','Pebble','Sprout','Petal','Moss','Acorn','Dewdrop','Fern','Mochi'][i%10],color:colors[(i+id)%colors.length],cells:canonical,width:d.w,height:d.h,allowedRotations:[0,1,2,3],solution:{x:gx,y:gy,rotation:goalRotation}}});
 const orientationRules=[];for(let i=0;i<Math.min(rotationRulesCount,pieces.length);i++)orientationRules.push({type:'orientation',pieceId:pieces[(i*3+id)%pieces.length].id,rotation:pieces[(i*3+id)%pieces.length].solution.rotation});
 const specialTiles=[],constraints=[...orientationRules];if(id>20){const piece=pieces[Math.floor(r()*pieces.length)],sol=piece.solution,shape=rotateShape(piece.cells,sol.rotation),cell={x:sol.x+shape[0].x,y:sol.y+shape[0].y};specialTiles.push({x:cell.x,y:cell.y,kind:'flower'});constraints.push({type:'cover',pieceId:piece.id,cell,kind:'flower'})}if(id>50){const piece=pieces[Math.floor(r()*pieces.length)],shape=rotateShape(piece.cells,piece.solution.rotation),cell={x:piece.solution.x+shape[shape.length-1].x,y:piece.solution.y+shape[shape.length-1].y};specialTiles.push({x:cell.x,y:cell.y,kind:'water'});constraints.push({type:'cover',pieceId:piece.id,cell,kind:'water'})}if(id>80&&pieces.length>1){let a=pieces[0],b=pieces.at(-1);const cellsA=rotateShape(a.cells,a.solution.rotation).map(c=>({x:c.x+a.solution.x,y:c.y+a.solution.y})),cellsB=rotateShape(b.cells,b.solution.rotation).map(c=>({x:c.x+b.solution.x,y:c.y+b.solution.y})),touch=cellsA.some(c=>cellsB.some(d=>Math.abs(c.x-d.x)+Math.abs(c.y-d.y)===1));if(!touch)constraints.push({type:'not-touch',a:a.id,b:b.id})}
 const piecesById=Object.fromEntries(pieces.map(p=>[p.id,p])),solution=Object.fromEntries(pieces.map(p=>[p.id,{...p.solution}]));
 const rules=orientationRules.map(c=>`Turn ${piecesById[c.pieceId].name} to ${c.rotation*90}°.`);for(const c of constraints.filter(q=>q.type==='cover'))rules.push(`Place ${piecesById[c.pieceId].name} over ${c.kind==='flower'?'🌸 flower':'💧 water'}.`);for(const c of constraints.filter(q=>q.type==='not-touch'))rules.push(`Keep ${piecesById[c.a].name} and ${piecesById[c.b].name} from touching edges.`);
 const mechanic=id<=20?'Shape fit':id<=50?'Rotation fit':id<=80?'Rocks & shapes':id<=105?'Special tiles':'Garden rule mix';
 const diff=Number((1+id/120*9).toFixed(1));const p={id,type:'packing',mechanic,tier,title:`${['Mossy nook','Turnabout garden','Pebble path','Petal puzzle','Mochi’s maze'][Math.min(4,Math.floor((id-1)/24))]} ${String(id).padStart(3,'0')}`,instructions:'Fit every piece onto the garden board. Pieces must cover each open cell exactly once.',difficulty:diff,data:{cols:g.cols,rows:g.rows,blocked,pieces,specialTiles,constraints,rules,solution,playableCells:playable},hints:[`Look for the board corners and match their edges with a piece.`,`Try turning the ${pieces[0].name} piece; its outline fits a useful corner.`,`The ${pieces[0].name} piece belongs near row ${pieces[0].solution.y+1}, column ${pieces[0].solution.x+1}.`],reward:{coins:tier.includes('Tutorial')?20:tier.startsWith('Easy')?28:tier==='Medium'?38:tier==='Hard'?52:75,xp:tier.includes('Tutorial')?10:tier.startsWith('Easy')?16:tier==='Medium'?24:tier==='Hard'?38:55},validated:false};p.solution=p.data.solution;return p}

function constraintFailure(p,placed){const byId=Object.fromEntries(p.data.pieces.map(x=>[x.id,x]));for(const c of p.data.constraints){if(c.type==='orientation'&&placed[c.pieceId]?.rotation!==c.rotation)return`Turn ${byId[c.pieceId].name} to ${c.rotation*90}° (currently ${placed[c.pieceId]?.rotation*90||0}°).`;if(c.type==='cover'){const piece=byId[c.pieceId],pos=placed[c.pieceId],cells=rotateShape(piece.cells,pos.rotation).map(q=>({x:q.x+pos.x,y:q.y+pos.y}));if(!cells.some(q=>q.x===c.cell.x&&q.y===c.cell.y))return`Place ${piece.name} over the ${c.kind==='flower'?'🌸 flower':'💧 water'} tile.`}if(c.type==='not-touch'){const a=byId[c.a],b=byId[c.b],pa=placed[c.a],pb=placed[c.b],ca=rotateShape(a.cells,pa.rotation).map(q=>({x:q.x+pa.x,y:q.y+pa.y})),cb=rotateShape(b.cells,pb.rotation).map(q=>({x:q.x+pb.x,y:q.y+pb.y}));if(ca.some(x=>cb.some(y=>Math.abs(x.x-y.x)+Math.abs(x.y-y.y)<=1)))return`${a.name} and ${b.name} cannot touch edges.`}}return''}
function constraintOk(p,placed){return !constraintFailure(p,placed)}
export function validateState(p,placements){const d=p.data,blocked=new Set(d.blocked.map(c=>`${c.x},${c.y}`)),occ=new Map();for(const piece of d.pieces){const pos=placements?.[piece.id];if(!pos||!Number.isInteger(pos.x)||!Number.isInteger(pos.y)||!Number.isInteger(pos.rotation))return{valid:false,reason:'Place every piece on the board.'};if(piece.allowedRotations&&!piece.allowedRotations.includes(pos.rotation))return{valid:false,reason:'That turn is not allowed.'};for(const c of rotateShape(piece.cells,pos.rotation)){const x=pos.x+c.x,y=pos.y+c.y,k=`${x},${y}`;if(x<0||x>=d.cols||y<0||y>=d.rows)return{valid:false,reason:'Keep every tile inside the board.'};if(blocked.has(k))return{valid:false,reason:'A piece is covering a rock.'};if(occ.has(k))return{valid:false,reason:'Pieces cannot overlap.'};occ.set(k,piece.id)}}if(occ.size!==d.playableCells.length||d.playableCells.some(c=>!occ.has(`${c.x},${c.y}`)))return{valid:false,reason:'A few open garden cells still need a piece.'};const ruleFailure=constraintFailure(p,placements);if(ruleFailure)return{valid:false,reason:ruleFailure};return{valid:true}}
export function isSolved(p,s){return validateState(p,s?.placements).valid}

// Independent exact-cover search: choose the most constrained uncovered cell,
// try every legal piece orientation and placement, then check all global rules.
export function solvePuzzle(p,maxNodes=1000000){const d=p.data,blocked=new Set(d.blocked.map(c=>`${c.x},${c.y}`)),target=new Set(d.playableCells.map(c=>`${c.x},${c.y}`)),pieces=d.pieces,byId=Object.fromEntries(pieces.map(q=>[q.id,q])),variants={};for(const piece of pieces){variants[piece.id]=[];for(const rot of piece.allowedRotations||[0,1,2,3]){if(d.constraints.some(c=>c.type==='orientation'&&c.pieceId===piece.id&&c.rotation!==rot))continue;const shape=rotateShape(piece.cells,rot);for(let y=0;y<d.rows;y++)for(let x=0;x<d.cols;x++){const cells=shape.map(c=>`${x+c.x},${y+c.y}`);if(cells.every(k=>target.has(k)&&!blocked.has(k)))variants[piece.id].push({x,y,rotation:rot,cells})}}}let nodes=0;const search=(occupied,placed,remaining)=>{if(++nodes>maxNodes)return false;if(!remaining.length)return occupied.size===target.size&&constraintOk(p,placed);let best=null;for(const cell of target){if(occupied.has(cell))continue;let options=[];for(const id of remaining)for(const v of variants[id])if(v.cells.includes(cell)&&v.cells.every(k=>!occupied.has(k)))options.push({id,v});if(!best||options.length<best.length)best=options;if(!best.length)return false}for(const{id,v}of best||[]){const nextOcc=new Set(occupied);v.cells.forEach(k=>nextOcc.add(k));const nextPlaced={...placed,[id]:{x:v.x,y:v.y,rotation:v.rotation}};if(search(nextOcc,nextPlaced,remaining.filter(q=>q!==id)))return true}return false};return search(new Set(),{},pieces.map(p=>p.id))}
export const puzzles=Array.from({length:120},(_,i)=>makePuzzle(i+1));
for(const p of puzzles){const placementCheck=validateState(p,p.solution);if(!placementCheck.valid)throw new Error(`Packing puzzle ${p.id} solution invalid: ${placementCheck.reason}`);p.validated=true}
