import React,{useEffect,useMemo,useRef,useState}from'react';
import{RotateCw,Undo2,Move}from'lucide-react';
import{rotateShape,validateState}from'./puzzles.js';

const shapeBounds=cells=>({w:Math.max(...cells.map(c=>c.x))+1,h:Math.max(...cells.map(c=>c.y))+1});
const blankPlacements=p=>Object.fromEntries(p.data.pieces.map(q=>[q.id,{x:null,y:null,rotation:0}]));
function boardValidity(p,pieceId,pos,placements){const d=p.data,piece=d.pieces.find(q=>q.id===pieceId),blocked=new Set(d.blocked.map(c=>`${c.x},${c.y}`));for(const c of rotateShape(piece.cells,pos.rotation)){const x=pos.x+c.x,y=pos.y+c.y,key=`${x},${y}`;if(x<0||x>=d.cols||y<0||y>=d.rows)return{valid:false,reason:'That shape would hang over the board.'};if(blocked.has(key))return{valid:false,reason:'A piece cannot cover a rock.'};for(const other of d.pieces){if(other.id===pieceId)continue;const op=placements[other.id];if(!Number.isInteger(op?.x))continue;if(rotateShape(other.cells,op.rotation).some(q=>q.x+op.x===x&&q.y+op.y===y))return{valid:false,reason:'Pieces need their own space.'}}}return{valid:true}}

export function PuzzleTable({puzzle,onSolved,onMove,hintLevel=0,onMessage,onSound=()=>{}}){const rootRef=useRef(null),boardRef=useRef(null),dragRef=useRef(null),solvedRef=useRef(false);const[placements,setPlacements]=useState(()=>blankPlacements(puzzle)),[selectedId,setSelectedId]=useState(puzzle.data.pieces[0]?.id||null),[drag,setDrag]=useState(null),[notice,setNotice]=useState(''),[failCount,setFailCount]=useState(0),[invalidTick,setInvalidTick]=useState(0),[cellSize,setCellSize]=useState(48);const d=puzzle.data,pieces=d.pieces,selected=pieces.find(p=>p.id===selectedId),specialMap=useMemo(()=>new Map(d.specialTiles.map(t=>[`${t.x},${t.y}`,t.kind])),[d.specialTiles]);
 useEffect(()=>{const resize=()=>setCellSize(Math.min(54,Math.max(32,(window.innerWidth-70)/d.cols)));resize();window.addEventListener('resize',resize);return()=>window.removeEventListener('resize',resize)},[d.cols]);
 const tell=msg=>{setNotice(msg);onMessage?.(msg);setTimeout(()=>setNotice(''),1900)};
 function candidateAt(e,activeDrag){const rect=boardRef.current?.getBoundingClientRect();if(!rect)return null;const inset=Number.parseFloat(getComputedStyle(boardRef.current).getPropertyValue('--board-inset'))||12,cw=(rect.width-inset*2)/d.cols,ch=(rect.height-inset*2)/d.rows,col=Math.floor((e.clientX-rect.left-inset)/cw),row=Math.floor((e.clientY-rect.top-inset)/ch);if(col<0||col>=d.cols||row<0||row>=d.rows)return null;return{x:col-activeDrag.anchor.x,y:row-activeDrag.anchor.y,rotation:activeDrag.rotation}}
 function beginDrag(e,pieceId,anchor){if(e.button!==undefined&&e.button!==0)return;const piece=pieces.find(p=>p.id===pieceId),current=placements[pieceId],rot=current.rotation||0;setSelectedId(pieceId);onSound('snap');const useAnchor=anchor||{x:0,y:0};dragRef.current={pieceId,anchor:useAnchor,rotation:rot,startX:e.clientX,startY:e.clientY,moved:false};try{rootRef.current?.setPointerCapture(e.pointerId)}catch{}}
 function pointerMove(e){const g=dragRef.current;if(!g)return;const moved=Math.hypot(e.clientX-g.startX,e.clientY-g.startY)>6;if(!moved)return;g.moved=true;const candidate=candidateAt(e,g);setDrag(candidate?{pieceId:g.pieceId,...candidate,validity:boardValidity(puzzle,g.pieceId,candidate,placements)}:null)}
 function maybeSolved(next){if(solvedRef.current)return;const result=validateState(puzzle,next);if(result.valid){solvedRef.current=true;onSolved(next);return}if(pieces.every(piece=>Number.isInteger(next[piece.id]?.x)&&Number.isInteger(next[piece.id]?.y)))tell(result.reason)}
 function pointerUp(e){const g=dragRef.current;if(!g)return;dragRef.current=null;setDrag(null);if(!g.moved)return;onMove?.();const candidate=candidateAt(e,g);if(!candidate){const n=failCount+1;setFailCount(n);setInvalidTick(x=>x+1);onSound('error');tell(n>=3?`Mochi: Try the ${pieces[0].name} piece first!`:'A gentle nudge—drop a piece over the board.');return}const check=boardValidity(puzzle,g.pieceId,candidate,placements);if(!check.valid){const n=failCount+1;setFailCount(n);setInvalidTick(x=>x+1);onSound('error');tell(n>=3?`Mochi: Try moving the ${pieces[0].name} piece first!`:check.reason);return}const next={...placements,[g.pieceId]:candidate};setPlacements(next);setFailCount(0);setSelectedId(g.pieceId);onSound('snap');maybeSolved(next)}
 function cancelDrag(){dragRef.current=null;setDrag(null)}
 function rotateSelected(){if(!selected)return;const cur=placements[selected.id],candidate={...cur,rotation:((cur.rotation||0)+1)%4};if(Number.isInteger(cur.x)){const check=boardValidity(puzzle,selected.id,candidate,placements);if(!check.valid){setInvalidTick(x=>x+1);onSound('error');tell(check.reason);return}}const next={...placements,[selected.id]:candidate};setPlacements(next);onMove?.();tell(`${selected.name} turned ${candidate.rotation*90}°`);if(Number.isInteger(candidate.x))maybeSolved(next)}
 function returnSelected(){if(!selected||!Number.isInteger(placements[selected.id]?.x))return;const next={...placements,[selected.id]:{x:null,y:null,rotation:placements[selected.id].rotation}};setPlacements(next);onMove?.();solvedRef.current=false}
 function placeByTap(pieceId,x,y){const pos=placements[pieceId],candidate={x,y,rotation:pos.rotation||0},check=boardValidity(puzzle,pieceId,candidate,placements);onMove?.();if(!check.valid){setInvalidTick(n=>n+1);tell(check.reason);return}const next={...placements,[pieceId]:candidate};setPlacements(next);setSelectedId(pieceId);onSound('snap');maybeSolved(next)}
 function boardClick(e,x,y){if(e.target.closest('.board-piece-layer'))return;if(!selectedId)return;placeByTap(selectedId,x,y)}
 function handleKeys(e){if(e.key.toLowerCase()==='r'){e.preventDefault();rotateSelected()}if(e.key==='Escape'){setSelectedId(null)}}
 const solutionPiece=hintLevel>=3?pieces[0]:null,solutionPos=solutionPiece?solutionPiece.solution:null,solutionShape=solutionPiece?rotateShape(solutionPiece.cells,solutionPos.rotation):[];
 const cells=[];for(let y=0;y<d.rows;y++)for(let x=0;x<d.cols;x++){const blocked=d.blocked.some(c=>c.x===x&&c.y===y),kind=specialMap.get(`${x},${y}`);cells.push(<div key={`${x},${y}`} role="gridcell" aria-label={blocked?'Rock tile':kind?`${kind} tile`:`Board cell row ${y+1}, column ${x+1}`} className={`board-cell ${blocked?'rock-cell':''} ${kind?`special-${kind}`:''}`} onClick={e=>!blocked&&boardClick(e,x,y)}>{kind&&<span className="board-marker">{kind==='water'?'💧':'🌸'}</span>}{blocked&&<span className="rock-marker">✿</span>}</div>)}
 const placedTiles=[];for(const piece of pieces){const pos=placements[piece.id];if(!Number.isInteger(pos?.x))continue;const shape=rotateShape(piece.cells,pos.rotation);for(const c of shape){const tileKind=specialMap.get(`${pos.x+c.x},${pos.y+c.y}`);placedTiles.push(<button key={`${piece.id}-${c.x}-${c.y}`} className={`board-piece-cell ${selectedId===piece.id?'selected':''}`} style={{gridColumn:pos.x+c.x+1,gridRow:pos.y+c.y+1,'--piece-color':piece.color}} aria-label={`${piece.name} tile${tileKind?`, covering ${tileKind}`:''}`} data-piece-cell="true" data-piece-id={piece.id} data-cell-x={c.x} data-cell-y={c.y} onPointerDown={e=>beginDrag(e,piece.id,c)}>{tileKind&&<span className="piece-special-marker" aria-hidden="true">{tileKind==='flower'?'🌸':'💧'}</span>}</button>);}}
 const ghostTiles=[];if(drag){const piece=pieces.find(p=>p.id===drag.pieceId),shape=rotateShape(piece.cells,drag.rotation);for(const c of shape){const x=drag.x+c.x,y=drag.y+c.y;if(x>=0&&x<d.cols&&y>=0&&y<d.rows)ghostTiles.push(<div key={`g-${x}-${y}`} className={`ghost-piece-cell ${drag.validity?.valid?'ghost-valid':'ghost-invalid'}`} style={{gridColumn:x+1,gridRow:y+1,'--piece-color':piece.color}}/>)} }
 const hintTiles=[];if(solutionPiece&&solutionPos&& !Number.isInteger(placements[solutionPiece.id]?.x)){for(const c of solutionShape)hintTiles.push(<div key={`h-${c.x}-${c.y}`} className="hint-piece-cell" style={{gridColumn:solutionPos.x+c.x+1,gridRow:solutionPos.y+c.y+1}}/>)}
 return <div ref={rootRef} className="packing-game" onPointerDown={e=>{const target=e.target.closest('[data-piece-cell]');if(!target)return;beginDrag(e,target.dataset.pieceId,{x:Number(target.dataset.cellX),y:Number(target.dataset.cellY)})}} onPointerMove={pointerMove} onPointerUp={pointerUp} onPointerCancel={cancelDrag} onKeyDown={handleKeys}>
  <div className="packing-brief"><div className="brief-copy"><div className="brief-eyebrow">MOCHI’S GARDEN CHALLENGE</div><b>Fit every shape into the open spaces.</b><span>Drag a piece, drop it on the board, and rotate it when it helps.</span></div><div className="brief-mochi">🐸 <i>{notice||'Can you solve this one?'}</i></div></div>
  <div className={`puzzle-table ${invalidTick?`nudge-${invalidTick%2}`:''}`} key={puzzle.id}>
   <div className="packing-board-frame"><div className="packing-board" ref={boardRef} role="grid" aria-label={`${d.cols} by ${d.rows} garden puzzle board`} style={{'--board-inset':'12px',width:`${cellSize*d.cols+24}px`,height:`${cellSize*d.rows+24}px`,gridTemplateColumns:`repeat(${d.cols},${cellSize}px)`,gridTemplateRows:`repeat(${d.rows},${cellSize}px)`}}>{cells}<div className="board-piece-layer" style={{gridTemplateColumns:`repeat(${d.cols},${cellSize}px)`,gridTemplateRows:`repeat(${d.rows},${cellSize}px)`}}>{placedTiles}{hintTiles}{ghostTiles}</div></div><div className="board-legend"><span>🌸 cover the blossom</span><span>💧 cover the pond tile</span><span>✿ rock · keep clear</span></div></div>
   <aside className="piece-panel"><div className="piece-panel-title"><div><small>YOUR PIECES</small><b>{pieces.filter(p=>Number.isInteger(placements[p.id]?.x)).length} / {pieces.length} placed</b></div><span>Drag onto board</span></div><div className="piece-tray">{pieces.map(piece=>{const pos=placements[piece.id],shape=rotateShape(piece.cells,pos.rotation||0),bound=shapeBounds(shape),isPlaced=Number.isInteger(pos.x),locked=hintLevel>=2&&piece.id===pieces[0].id,turnRule=d.constraints.find(c=>c.type==='orientation'&&c.pieceId===piece.id),coverRule=d.constraints.find(c=>c.type==='cover'&&c.pieceId===piece.id);return <button key={piece.id} className={`tray-piece ${selectedId===piece.id?'chosen':''} ${isPlaced?'in-board':''} ${locked?'hinted':''} ${drag?.pieceId===piece.id?'being-dragged':''}`} aria-label={`${piece.name} piece${isPlaced?' on board':''}`} onClick={()=>{setSelectedId(piece.id);onSound('click')}}><div className="tray-shape" style={{gridTemplateColumns:`repeat(${bound.w},19px)`,gridTemplateRows:`repeat(${bound.h},19px)`}} data-piece-cell="true" data-piece-id={piece.id} data-cell-x="0" data-cell-y="0">{shape.map(c=><span key={`${c.x}-${c.y}`} className="tray-shape-cell" style={{gridColumn:c.x+1,gridRow:c.y+1,'--piece-color':piece.color}} data-piece-cell="true" data-piece-id={piece.id} data-cell-x={c.x} data-cell-y={c.y}/>)}</div><span className="tray-label">{piece.name}</span>{turnRule&&<i className={`turn-mark ${pos.rotation===turnRule.rotation?'turn-ok':'turn-required'}`}>↻ {pos.rotation*90}° / {turnRule.rotation*90}°</i>}{coverRule&&<i className="special-mark">{coverRule.kind==='flower'?'🌸':'💧'}</i>}</button>})}</div>
    <div className="piece-controls"><span className="selected-label">{selected?`Selected: ${selected.name}`:'Select a piece'}</span><button className="rotate-control" disabled={!selected} onClick={rotateSelected}><RotateCw size={17}/> Rotate 90°</button><button className="return-control" disabled={!selected||!Number.isInteger(placements[selected.id]?.x)} onClick={returnSelected}><Undo2 size={16}/> Return</button></div>
    <div className="rule-list"><b>Garden rules</b><span>Every open cell must be filled. Pieces cannot overlap or cover rocks.</span>{d.rules.map((rule,i)=><span key={i}>✦ {rule}</span>)}</div>
   </aside>
  </div>
  {notice&&<div className="puzzle-notice" role="status">{notice}</div>}
  <div className="packing-footnote"><Move size={14}/> Tap a piece, then a board cell to place it. Press <kbd>R</kbd> to rotate.</div>
 </div>
}
